version: "3.8"
services:
  db:
    image: postgres:15
    container_name: postgres-morango
    environment:
      POSTGRES_DB: morango
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend-morango
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/morango
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345678

  frontend:
    build: ./frontend
    container_name: frontend-morango
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: